# Generated by Django 4.0.3 on 2022-10-16 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_distance', models.IntegerField(default=-1, verbose_name='Color distance')),
                ('fullness', models.FloatField(verbose_name='Fullness')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size', models.IntegerField(verbose_name='Max size')),
                ('frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rock', to='main_app.frame', verbose_name='Frame')),
            ],
        ),
    ]
